name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  # Every 2 days at 04:00PM
  schedule: [{cron: "0 16 */2 * *"}]
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.TOKEN }}
          template: classic
          filename: "metrics.svg"
          # output_action: gist
          # committer_gist: ${{ secrets.TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: issue,pr,review,wiki
          plugin_activity_limit: 4
          plugin_activity_load: 300
          plugin_activity_visibility: all
